### ISSUE TITLE
multiple playlists

### ISSUE THREAD

**Issue by alexanderek** [m8tec/Deezync#1]
Hi!

Does it support only one playlist?

**Comment by m8tec** [comment]
Hey, you can add as many playlists as you want to the config

**Comment by alexanderek** [comment]
Could you provide an example of how to specify multiple list in config.yml?

**Comment by m8tec** [comment]
Sure, that would be the example config with two playlists. `PLAYLIST_ID_X` is the placeholder for your different playlist ids. Hope that helps

```
plex_token: # token of your Plex server
plex_server: # name of your Plex server
plex_library: # name of your Plex music library
deezer_playlists:
  - id: PLAYLIST_ID_1 # your (first) deezer playlist id
    bitrate: 9 # FLAC = 9, MP3_320 = 3, MP3_128 = 1
    delete_unmatched_from_playlist: 0
    active: 1
    sync_interval_seconds: 3600
    sync_cover_description: 1
  - id: PLAYLIST_ID_2 # your (second) deezer playlist id
    bitrate: 9 # FLAC = 9, MP3_320 = 3, MP3_128 = 1
    delete_unmatched_from_playlist: 0
    active: 1
    sync_interval_seconds: 3600
    sync_cover_description: 1
```
